name:       Bipolar
pygments:   true
markdown:   redcarpet
port:       3000
exclude:    [Gemfile, Gemfile.lock, Guardfile, bin, _assets]
navigation:
  -
    text: "Blog"
    url: "/index.html"
  -
    text: "About"
    url: "/about/index.html"
authors:
  matija:
    name: "Matija Marohnić"
    nick: "matija"
    email: "matija.marohnic@gmail.com"
    twitter: "silvenon"
    github: "silvenon"
  janko:
    name: "Janko Marohnić"
    nick: "janko"
    email: "janko.marohnic@gmail.com"
    twitter: "m_janko"
    github: "janko-m"
