name:             Bipolar
description:      "A Ruby/Node-oriented blog about design & development."
baseurl:          ""
url:              "http://twin.github.io"

port:             4000
highlighter:      pygments
markdown:         redcarpet
redcarpet:
  extensions:     ["smart", "superscript", "autolink"]
exclude:          [Gemfile, Gemfile.lock, .gitignore, .sass-cache]
permalink:        /:year/:month/:title/
history:          "//github.com/twin/twin.github.io/commits/master/"

gems:
  - jemoji

sass:
  sass_dir:       styles

authors:
  janko:
    name:         "Janko Marohnić"
    identifier:   "janko"
    social:
      Twitter:    "//twitter.com/jankomarohnic"
      GitHub:     "//github.com/janko-m"
      Email:      "mailto:janko.marohnic@gmail.com"
      Facebook:   "//facebook.com/janko.marohnic"

  matija:
    name:         "Matija Marohnić"
    identifier:   "matija"
    social:
      Twitter:    "//twitter.com/silvenon"
      GitHub:     "//github.com/silvenon"
      Email:      "mailto:matija.marohnic@gmail.com"
      Instagram:  "//instagram.com/silvenon"
      Vine:       "//vine.co/silvenon"
      SoundCloud: "//soundcloud.com/silvenon"
      Facebook:   "//facebook.com/matijamm"
